[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 